bug fixd. Ordering of fields in where clause was messedup causing replication errors.
{{{
2008-03-11 15:33:22,475:TRACE db-meta - master for meta_set com.netblue.bruce.SlaveRunner - Applying change. xid:31270818 tid:291978448 tabname:bimp.partner_summary_200803 cmdtype:D info:day_id:int4:MjYyMw==:!|p:int8:MTkwMDAwMTkxOQ==:!|search_term:varchar:RG9vciBIYW5naW5n:!|is_new_user:int2:MA==:!|views:int8:MQ==:!|submits:int8:MA==:!|confirms:int8:MA==:!|revenue:int8:MA==:!|payout:int8:MA==:!|auctions:int8:!:!
2008-03-11 15:33:22,477:ERROR db-meta - master for meta_set com.netblue.bruce.SlaveRunner - Exception replicating to node db-meta - master for meta_set url jdbc:postgresql://ww-n02-2-db05/portaldb?user=bruce&password=bruce. thread will now sleep,init(),retry:
org.postgresql.util.PSQLException: ERROR: invalid input syntax for integer: "Door Hanging"
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:1525)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1309)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:188)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:452)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:354)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:347)
        at com.netblue.bruce.SlaveRunner.applyChanges(SlaveRunner.java:509)
        at com.netblue.bruce.SlaveRunner.applyAllChangesForResultSet(SlaveRunner.java:452)
        at com.netblue.bruce.SlaveRunner.applyAllChangesForTransaction2(SlaveRunner.java:431)
        at com.netblue.bruce.SlaveRunner.processSnapshot(SlaveRunner.java:336)
        at com.netblue.bruce.SlaveRunner.doWork(SlaveRunner.java:280)
        at com.netblue.bruce.SlaveRunner.run(SlaveRunner.java:252)
        at java.lang.Thread.run(Thread.java:595)
}}}


git-svn-id: file:///home/mgrosso/data/svn-elvis/trunk@157 2e195dce-9def-4caf-bb7c-8c699b2d911e